import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'errors/index': 'src/errors/index.ts',
    'cost/index': 'src/cost/index.ts',
    'semantic/index': 'src/semantic/index.ts',
    'storage/index': 'src/storage/index.ts',
    'storage/redis': 'src/storage/redis.ts',
    'storage/upstash': 'src/storage/upstash.ts',
    'storage/cloudflare-kv': 'src/storage/cloudflare-kv.ts',
    'storage/vercel-kv': 'src/storage/vercel-kv.ts',
    'storage/sqlite': 'src/storage/sqlite.ts',
    'storage/postgres': 'src/storage/postgres.ts',
    'embeddings/index': 'src/embeddings/index.ts',
    'embeddings/openai': 'src/embeddings/openai.ts',
    'embeddings/cohere': 'src/embeddings/cohere.ts',
    'embeddings/voyage': 'src/embeddings/voyage.ts',
    'adapters/openai/index': 'src/adapters/openai/index.ts',
    'adapters/anthropic/index': 'src/adapters/anthropic/index.ts',
    'adapters/ai-sdk/index': 'src/adapters/ai-sdk/index.ts',
    'adapters/langchain/index': 'src/adapters/langchain/index.ts',
    'adapters/hono/index': 'src/adapters/hono/index.ts',
    'adapters/express/index': 'src/adapters/express/index.ts',
    'adapters/next/index': 'src/adapters/next/index.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  minify: false,
  treeshake: true,
  splitting: false,
  target: 'es2022',
  outDir: 'dist',
  tsconfig: 'tsconfig.build.json',
  external: [
    'openai',
    '@anthropic-ai/sdk',
    'ai',
    '@langchain/core',
    'ioredis',
    '@upstash/redis',
    'better-sqlite3',
    '@vercel/kv',
    'pg',
    'postgres',
    'cohere-ai',
    'hono',
    'express',
    'next',
  ],
});
